os: osx
language: minimal

env:
- TARGET=setup-home	
- TARGET=setup-work
- TARGET=lint
- TARGET=show-help

cache:
  directories:
    - /usr/local/Caskroom
    - /usr/local/Cellar
    - /usr/local/Frameworks
    - /usr/local/Homebrew

script: |
  brew remove swiftlint
  sed -i '' '/steam/d' ./brew/Brewfile
  sed -i '' '/virtualbox/d' ./brew/Brewfile

  make -j "$(sysctl -n hw.ncpu)" "$TARGET"
