os: osx
language: minimal

env:
- TARGET=lint
- TARGET=show-help

script: sed -i '' '/steam/d' ./brew/Brewfile && sed -i '' '/virtualbox/d' ./brew/Brewfile && make -j "$(sysctl -n hw.ncpu)" "$TARGET"
