os: osx
language: minimal

env:
- TARGET=setup-home	
- TARGET=setup-work
- TARGET=lint
- TARGET=show-help

cache:
  directories:
    - /Users/travis/Library/Caches/Homebrew

before_script:
  - brew uninstall swiftlint
  - brew uninstall php
  - sed -i '' '/steam/d' ./brew/Brewfile
  - sed -i '' '/virtualbox/d' ./brew/Brewfile

script:
  - make -j "$(sysctl -n hw.ncpu)" "$TARGET"
