[env_var]
variable = "SHELL_NAME"
default = "unknown"
style	= "bold white"

[character]      # The name of the module we are configuring is "character"
symbol = ""     # The "symbol" segment is being set to "➜"
